### ISSUE TITLE
Retail ADO pipeline fails to restore and build any version of Microsoft.Build.NoTargets other than 3.3.0

### ISSUE THREAD

**Issue by abatishchev** [microsoft/MSBuildSdks#432]
I have 2 repos: Client contains the build pipeline and Service the files to be built:

```
- Service
global.json contains "Microsoft.Build.NoTargets": "3.7.0"
/src
  Host.proj contains <Project Sdk="Microsoft.Build.NoTargets">
- Client
build.yml
```

Until the build pipeline does this using PowerShell:

```powershell
$path = '$(OutputRoot)\Host.proj'
[xml]$proj = Get-Content -Path $path
$proj.Project.Sdk = 'Microsoft.Build.NoTargets/3.3.0'
$proj.Save($path)
```

It fails to restore the packages with an error:

```
error : Could not resolve SDK "Microsoft.Build.NoTargets". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
error :   The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.Build.NoTargets" because directory "C:\Program Files\dotnet\sdk\7.0.201\Sdks\Microsoft.Build.NoTargets\Sdk" did not exist.
```

Copying global.json to any of the folder (Client repo's root, Host project's root, output folder) makes no difference.

Nor specifying this at the beginning of the pipeline:

```yml
- task: UseDotNet@2
  displayName: 'Install .NET 6.x'
  inputs:
    packageType: sdk
    version: '6.x'
    performMultiLevelLookup: true

    useGlobalJson: true
    workingDirectory: '$(RepoRoot)\Host\'
```

Moreover, the .NET SDK 6.0 is installed:
```
Tool to install: .NET Core sdk version 6.x.
Found version 6.0.407 in channel 6.0 for user specified version spec: 6.x
Version 6.0.407 was not found in cache.
Getting URL to download .NET Core sdk version: 6.0.407.
Detecting OS platform to find correct download package for the OS.
Primary:win-x64
Detected platform (Primary): win-x64
Successfully installed .NET Core sdk version 6.0.407.
Creating global tool path and pre-pending to PATH.
```

but then ignored:

```
Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.201
```

Logs with debug turned on: https://dev.azure.com/msazure/One/_build/results?buildId=70654276&view=logs&j=9896b2a3-9399-5ea2-601e-3e68ab28a5c9&t=e38d4c4e-1438-5430-25cc-68a066e9d141

**Comment by abatishchev** [comment]
@jeffkl how can I collect bin log if the build fails at `nuget restore` step:

```yml
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(OutputRoot)\Host\Host.proj'
    feedsToUse: config
    nugetConfigPath: '$(RepoRoot)\Host\NuGet.config'
```

Here's what I tried to set before the task above:

```powershell
 $env:NUGET_RESTORE_MSBUILD_ARGS = '-bl:$(OutputRoot)\restore.binlog'
```

But it doesn't seem to work. Please suggest the right way to collect the logs.

**Comment by abatishchev** [comment]
Bummer, doesn't work :(

IUn the [debug logs](https://dev.azure.com/msazure/One/_build/results?buildId=70830686&view=logs&j=9896b2a3-9399-5ea2-601e-3e68ab28a5c9&t=e38d4c4e-1438-5430-25cc-68a066e9d141&l=56), the argument being passed:

```
##[debug]arguments=/binarylogger:LogFile=D:\a\_temp\msbuild.binlog
```

Then the restore fails. But uploading the build artifacts fails too:

```
##[debug]PathtoPublish=D:\a\_temp\msbuild.binlog
##[debug]check path : D:\a\_temp\msbuild.binlog
##[debug]task result: Failed
##[error]Publishing build artifacts failed with an error: Not found PathtoPublish: D:\a\_temp\msbuild.binlog
```

**Comment by jeffkl** [comment]
Oops for `dotnet restore` you need to use a different argument, `restoreArguments`.

![image](https://user-images.githubusercontent.com/17556515/228333554-850cf685-5dfd-4a46-be02-12abd504c229.png)
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines

```yml
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    restoreArguments: '/binarylogger:LogFile=$(RepoRoot)\msbuild.binlog'
    projects: '$(RepoRoot)\Service\src\Host.proj'
    feedsToUse: config
    nugetConfigPath: '$(RepoRoot)\Service\NuGet.config'
```

**Comment by abatishchev** [comment]
yay! worked. attached the bin logs: [msbuild.binlog.zip](https://github.com/microsoft/MSBuildSdks/files/11093456/msbuild.binlog.zip)

**Comment by jeffkl** [comment]
Your build pipeline is copying the source projects to a new directory, `$(OutputRoot)` which is `D\a\1\s\out\ATSHost\ATSHost.proj`.  Is `global.json` in a parent folder of that?  If not, you'll need to copy `global.json` as well.  The SDK resolver only looks in the project directory and all of the parent folders.  Copying this project out of the repository before building will probably cause other issues and is a very unusual pattern.

![image](https://user-images.githubusercontent.com/17556515/228359015-f272d58f-40b9-454e-81b8-c641149f8d3a.png)

**Comment by abatishchev** [comment]
I've added this task:

```yaml
- task: CopyFiles@2
  displayName: 'Copy global.json'
  inputs:
    sourceFolder: '$(RepoRoot)\Service\'
    targetFolder: '$(OutputRoot)\Service\'
    contents: 'global.json'
```

And it works now! But it wasn't working before, I'm pretty sure - I have logs :)

Could have something changed between:

```
SDK Version: 7.0.201
```

and

```
SDK Version: 7.0.202
```

P.S.

> Copying this project out of the repository before building will probably cause other issues and is a very unusual pattern.

Yes :( It's a mess which I inherited and which is temporal, so I'm hesitant to do major refactoring, rather can't wait to abandon the whole thing.
